blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import send_mailing, IndexListView, MailingListView, MailingDetailView, MailingCreateView, \
    MailingUpdateView, MailingDeleteView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailingLogListView, \
    MessageCreateView, MessageUpdateView, MessageDetailView, MessageDeleteView, ClientListView

app_name = MailingConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_detail/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='message_detail'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing_log_list', MailingLogListView.as_view(), name='mailing_log_list'),
]

mailing/models.py
from django.utils import timezone

from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(
        verbose_name='Email',
        help_text='Enter email',
    )
    full_name = models.CharField(
        verbose_name='Full name',
        help_text='Enter your full name',
        max_length=100,
    )
    comment = models.TextField(
        verbose_name='Comment',
        help_text='Add a comment',
        max_length=200,
        **NULLABLE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='User',
        **NULLABLE
    )

    class Meta:
        verbose_name = 'Client'
        verbose_name_plural = 'Clients'

    def __str__(self):
        return f'{self.full_name} - {self.email}'


class Message(models.Model):
    subject = models.CharField(
        max_length=300
    )
    body = models.TextField()
    # user = models.ForeignKey(
    #     settings.AUTH_USER_MODEL,
    #     on_delete=models.CASCADE,
    #     verbose_name='User'
    # )

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'
        permissions = [
            ('can_not_edit_message', 'Can not edit message')
        ]

    def __str__(self):
        return self.subject


class MailingSettings(models.Model):
    FIRST_SEND_OPTIONS = (
        ('now', 'Instantly'),
        ('scheduled', 'Schedule'),
    )
    FREQUENCY_OPTIONS = (
        ('daily', 'Once a day'),
        ('weekly', 'Once a week'),
        ('monthly', 'Once a month'),
    )
    STATUS_OPTIONS = (
        ('created', 'Created'),
        ('running', 'Running'),
        ('completed', 'Completed'),
    )

    first_send = models.DateTimeField(
        default=timezone.now
    )
    frequency = models.CharField(
        max_length=15,
        choices=FREQUENCY_OPTIONS
    )
    status = models.CharField(
        max_length=25,
        choices=STATUS_OPTIONS,
        default='created'
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE
    )
    clients = models.ManyToManyField(
        Client,
        related_name='clients',
        verbose_name='Clients'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='User',
        **NULLABLE
    )

    class Meta:
        verbose_name = 'Mailing'
        verbose_name_plural = 'Mailings'
        permissions = [
            ('can_view_mailings', 'Can view all mailings'),
            ('can_stop_mailings', 'Can stop mailings'),
            ('can_not_change_mailings', 'Can not change mailings'),
        ]

    def __str__(self):
        return f'Mailing #{self.id}'


class SendingAttempt(models.Model):
    STATUS_OPTIONS = (
        ('success', 'Successful'),
        ('failure', 'Failed')
    )

    mailing = models.ForeignKey(
        MailingSettings,
        on_delete=models.CASCADE
    )
    timestamp = models.DateTimeField(
        default=timezone.now
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_OPTIONS
    )
    server_response = models.TextField(
        **NULLABLE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='User',
        **NULLABLE
    )

    class Meta:
        verbose_name = 'Attempt'
        verbose_name_plural = 'Attempts'

    def __str__(self):
        return f"Mailing Attempt #{self.mailing_id}"

mailing/forms.py
from django import forms
from mailing.models import MailingSettings, Client, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'clients':
                continue
            elif field_name == 'user':
                continue
            elif field_name == 'is_active':
                continue
            else:
                field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = MailingSettings
        fields = ['status', 'message', 'frequency']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)

    def clean_day(self):
        cleaned_data = self.cleaned_data['day']
        if 0 > cleaned_data > 31:
            raise forms.ValidationError('Invalid format')
        return cleaned_data


class MailingUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = MailingSettings
        exclude = ['is_active']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['user'].disabled = True


class MailingManagerUpdateForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = MailingSettings
        exclude = ['clients']

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subject'].disabled = True
        self.fields['body'].disabled = True
        self.fields['status'].disabled = True
        self.fields['first_send'].disabled = True
        self.fields['timestamp'].disabled = True
        self.fields['frequency'].disabled = True
        self.fields['user'].disabled = True


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ['full_name', 'email', 'comment']
        labels = {
            'full_name': 'Full name',
            'email': 'Email',
            'comment': 'Comment'
        }


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ['subject', 'body']

mailing/views.py
import random
from time import sleep

import pytz
from apscheduler.schedulers.background import BackgroundScheduler
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.core.management import call_command
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.urls import reverse_lazy
from django.utils import timezone

import smtplib

from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from blog.models import Blog
from mailing.forms import ClientForm, MailingForm, MessageForm, MailingUpdateForm, MailingManagerUpdateForm
from mailing.models import MailingSettings, SendingAttempt, Client, Message
from mailing.services import get_mailing_from_cache, get_messages_from_cache


@login_required
def send_mailing(request):
    zone = pytz.timezone(settings.TIME_ZONE)
    current_datetime = timezone.now().astimezone(zone)

    mailings = MailingSettings.objects.filter(owner=request.user, first_send__lte=current_datetime)

    for mailing in mailings:
        for client in mailings.clients.all():
            try:
                send_mail(
                    subject=mailing.message.subject,
                    message=mailing.message.body,
                    from_email=settings.EMAIL_HOST_USER,
                    recipient_list=[client.email],
                    fail_silently=False
                )

                #Register successful operation
                attempt = SendingAttempt.objects.create(
                    mailing=mailing,
                    status='success',
                    server_response='Message sent at' + str(timezone.now())
                )
                attempt.save()
            except smtplib.SMTPException as e:
                #Register unsuccessful operation
                attempt = SendingAttempt.objects.create(
                    mailing=mailing,
                    status='failure',
                    server_response='Failed to send message:' + str(e)
                )
                attempt.save()

        #Updating mailing status
        mailing.status = 'running'
        mailing.save()


scheduler = BackgroundScheduler()
scheduler.add_job(send_mailing, 'interval', seconds=600)
scheduler.start()


class IndexListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'object_list'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = list(queryset)
        random.shuffle(queryset)
        return queryset[:3]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailings_count = len(MailingSettings.objects.all())
        mailings_is_active_count = len(MailingSettings.objects.filter(status='running'))
        unique_clients_count = Client.objects.values('email').distinct().count()
        context['mailings_count'] = mailings_count
        context['mailings_is_active_count'] = mailings_is_active_count
        context['unique_clients_count'] = unique_clients_count
        return context


class ClientCreateView(CreateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.user = user
        client.save()
        return super().form_valid(form)


class ClientListView(ListView, LoginRequiredMixin):
    model = Client
    template_name = 'mailing/client_list.html'
    context_object_name = 'object_list'


class ClientDetailView(DetailView):
    model = Client
    template_name = 'mailing/client_detail.html'


class ClientUpdateView(UpdateView, LoginRequiredMixin):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    context_object_name = 'object_list'
    success_url = reverse_lazy('mailing:client_list')


class ClientDeleteView(DeleteView, LoginRequiredMixin):
    model = Client
    template_name = 'mailing/client_delete.html'
    success_url = reverse_lazy('mailing/client_list')


class MailingCreateView(CreateView, LoginRequiredMixin):
    model = MailingSettings
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def get(self, request, **kwargs):
        form = self.form_class(self.request.user, request.POST)
        return render(request, 'mailing/mailing_form.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.user, request.POST)

        if form.is_valid():
            clients = form.cleaned_data.get('clients')
            if not clients:
                form.add_error('clients', 'Choose one client.')
            mailing = form.save(commit=False)
            mailing.user = self.request.user
            mailing.save()
            form.save_m2m()
            return redirect(self.success_url)


class MailingListView(ListView):
    model = MailingSettings
    template_name = 'mailing/mailing_list.html'
    context_object_name = 'object_list'

    def get_queryset(self):
        return get_mailing_from_cache()


class MailingDetailView(DetailView):
    model = MailingSettings
    template_name = 'mailing/mailing_detail.html'


class MailingUpdateView(UpdateView, LoginRequiredMixin):
    model = MailingSettings
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return MailingUpdateForm
        if user.has_perm('mailing.can_stop_mailings'):
            return MailingManagerUpdateForm
        raise PermissionDenied


class MailingDeleteView(DeleteView, LoginRequiredMixin):
    model = MailingSettings
    template_name = 'mailing/mailing_delete.html'
    success_url = reverse_lazy('mailing/mailing_list')


class MailingLogListView(ListView):
    model = SendingAttempt
    template_name = 'mailing/mailing_log_list.html'
    context_object_name = 'object_list'


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailing:message_detail')

    def form_valid(self, form):
        if form.is_valid():
            message = form.save(commit=False)
            message.owner = self.request.user
            message.save()
            return redirect('mailing:message_detail', pk=message.pk)


class MessageDetailView(DetailView):
    model = Message
    template_name = 'mailing/message_detail.html'

    def get_queryset(self):
        return get_messages_from_cache()


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'mailing/message_form.html'
    success_url = reverse_lazy('mailing:message_detail')

    def form_valid(self, form):
        if form.is_valid():
            message = form.save()
            message.save()
            return redirect(self.success_url)


class MessageDeleteView(DeleteView):
    model = Message
    template_name = 'mailing/message_delete.html'
    success_url = reverse_lazy('mailing:index')

mailing/templates/mailing/client_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Are you sure you want to delete {{ object.full_name }} ?</h3>
                        <button><a type="submit" class="btn btn-danger">DELETE</a></button>
                        <button><a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Cancel</a></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <h3 class="card-title"> Client: {{ object.full_name }}</h3>
                    <div class=" mb-6"> Email: {{ object.email }}</div>
                    <div class=" mb-6"> Comment: {{ object.comment }}</div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'mailing:client_list' %}" class="btn btn-outline-primary mb-2 align-center">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">

                        {% if object %}
                        <h3>Edit client</h3>
                        {% else %}
                        <h3>Create client</h3>
                        {% endif %}

                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
            </div>
        </div>
        <p>
            <button type="submit" class="btn btn-success">Save</button>
            <button><a href="{% url 'mailing:client_list' %}" class="btn btn-warning">Cancel</a></button>
        </p>
    </form>
</div>
<br>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}
<title>Clients</title>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Clients list</h2>
    <h3 class="card-title"><a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Create new client</a>
    </h3>
    <br>
</main>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-2">
    {% for object in objects_list %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.full_name }}</h3>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> email: {{ object.email }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_detail' object.pk %}">View</a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_update' object.pk %}">Edit</a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:client_delete' object.pk %}">Delete</a>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailing_delete.html
{% extends 'mailing/base.html' %}


{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <h3 class="card-title">Are you sure you want to delete {{ object.name }} ?</h3>
                        <button><a type="submit" class="btn btn-danger">DELETE</a></button>
                        <button><a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Cancel</a></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}
{% block content %}
<br>
<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="cart-body">
                <div class="card-body">
                    {{ form }}
                    <h3 class="mb-2">Title: {{ object.name }}</h3>
                    <p class="mb-2">Body: {{ object.body }}</p>
                </div>
                <div class="card-footer">
                    {% if  object.is_active == True %}
                    <p class="mb-2">Active</p>
                    {% else %}
                    <p class="mb-2">Inactive</p>
                    {% endif %}
                    <p class="mb-2">{{ get_is_active }}</p>
                    <p class="mb-2">Status: {{ object.status }}</p>
                    <p class="mb-2">Started: {{ object.first_send }}</p>
                    <p class="mb-2">Stopped: {{ object.timestamp }}</p>
                    <div class=" mb-2"> Frequency: {{ object.get_frequency_display }}</div>
                    <div class=" mb-6"> Author: {{ object.user }}</div>
                    <input type="button" onclick="history.back();" value="Back"/>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        {% if object %}
                        <h3>Edit</h3>
                        {% else %}
                        <h3>Create new</h3>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {% manager_groups as manager_group %}
                    {% if user.groups.all.0 == manager_group %}
                    <div class="mb-3">
                        {{ form.is_active.label_tag }}{{ form.is_active }}
                    </div>
                    {% endif %}
                    <div class="mb-3">
                        {{ form.subject.label_tag }}{{ form.subject }}
                    </div>
                    <div class="mb-3">
                        {{ form.body.label_tag }}{{ form.body }}
                    </div>
                    <div class="mb-3">
                        {{ form.status.label_tag }}{{ form.status }}
                    </div>
                    <div class="mb-3">
                        {{ form.first_send.label_tag }}{{ form.first_send }}{{ form.first_send.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.timestamp.label_tag }}{{ form.timestamp }}{{ form.timestamp.help_text }}
                    </div>
                    <div class="mb-3">
                        {{ form.frequency.label_tag }}{{ form.frequency }}
                    </div>
                    <div class="mb-3">
                        {{ form.clients.label_tag }}{{ form.clients }}
                    </div>
                </div>
            </div>
        </div>
        <p>
            <button type="submit" class="btn btn-success">Save</button>
            <button><a href="{% url 'mailing:mailing_list' %}" class="btn btn-warning">Cancel</a></button>
        </p>
    </form>
</div>
<br>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Mailing</title>

<main role="main" class="inner cover">
    <h2 class="cover-heading">Mailing list</h2>
    {% if perms.mailing.add_mailing %}
    <h3 class="card-title"><a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">New mailing</a>
    </h3>
    {% endif %}
    <br>
</main>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in objects_list %}
    {% manager_groups as manager_group %}
    {% if user == object.user or user.groups.all.0 == manager_group %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.message }}</h3>
                {% if object.status == running %}
                <div class=" mb-2"> Active </div>
                {% else %}
                <div class=" mb-2"> Inactive </div>
                {% endif %}
            </div>
            <div class="card-body">
                <p class="card-text">{{ object.body|truncatechars:100 }}</p>
            </div>
            <div class="card-footer">
                <div class=" mb-2"> Author: {{ object.user }}</div>
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'mailing:mailing_detail' object.pk %}">Details</a>
                {% if user == object.user or user.groups.all.0 == manager_group %}
                <a class="btn btn-outline-primary "
                   href="{% url 'mailing:mailing_edit' object.pk %}">Edit</a>
                {% endif %}
                {% if user == object.user %}
                <a class="btn btn-outline-primary " href="{% url 'mailing:mailing_delete' object.pk %}">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
    <br>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
   <div class="container">
       <div class="row-6">
           <div class="col">
               <form class="row" method="post" enctype="multipart/form-data">
                   <div class="card">
                       <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       </div>
                       <button type="submit" class="btn btn-success">
                           {% if object %}
                               Save
                           {% else %}
                               Create
                           {% endif %}
                       </button>
                   </div>
               </form>
           </div>
       </div>
   </div>
{% endblock %}