blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .apps import UsersConfig
from .views import VerificationView, ErrorVerification, UserProfileView, UserManagerListView, \
    UserManagerProfileView, UserCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('verification/', VerificationView.as_view(), name='verification'),
    path('verification/error/', ErrorVerification.as_view(), name='verification_error'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('users_list/', UserManagerListView.as_view(), name='users_list'),
    path('profile_manager/<int:pk>/', UserManagerProfileView.as_view(), name='profile_manager'),
    ]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.models import NULLABLE

default_code = ''.join([str(random.randint(0, 9)) for _ in range(12)])


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='Email',
        help_text='Fill in your email address',
        unique=True
    )
    avatar = models.ImageField(
        verbose_name='Avatar',
        help_text='Add your photo',
        upload_to='users/',
        **NULLABLE
    )
    is_active = models.BooleanField(
        verbose_name='Active?',
        help_text='Activate user',
        default=True,
    )
    is_verified = models.BooleanField(
        verbose_name='Verified?',
        help_text='Verify email',
        default=False,
    )
    verification_code = models.CharField(
        verbose_name='Verification code',
        help_text='Fill in the code from email',
        max_length=15,
        default=default_code,
    )

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f' {self.email}'

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        permissions = [
            ('can_block_user', 'Can block users'),
            ('can_view_users', 'Can view users')
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mailing.forms import StyleFormMixin
from users.models import User


class UserCreateForm(UserCreationForm, StyleFormMixin):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email',  'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()
        self.fields['email'].disabled = True


class UserManagerForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('is_active',)

users/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, ListView

from config import settings
from users.forms import UserCreateForm, UserProfileForm, UserManagerForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserCreateForm
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('users:verification')

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            send_mail(
                subject='Email confirmation',
                message=f'Your code is {new_user.ver_code}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )
        return super().form_valid(form)


class VerificationView(TemplateView):
    template_name = 'users/verification.html'

    def post(self, request):
        verification_code = request.POST.get('verification_code')
        user_code = User.objects.filter(verification_code=verification_code).first()

        if user_code is not None and user_code.verification_code == verification_code:
            user_code.is_active = True
            user_code.save()
            return redirect('users:login')
        else:
            return redirect('users:verification_error')


class ErrorVerification(TemplateView):
    template_name = 'users/verification_error.html'
    success_url = reverse_lazy('users:verification')


class UserProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailing:index')

    def get_object(self, queryset=None):
        return self.request.user


class UserManagerProfileView(UpdateView):
    model = User
    form_class = UserManagerForm
    template_name = 'users/profile_manager.html'
    success_url = reverse_lazy('users:users_list')


class UserManagerListView(ListView):
    model = User
    template_name = 'users/users_list.html'
    context_object_name = 'objects_list'

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
   <div class="container">
       <div class="row-6">
           <div class="col">
               <form class="row" method="post" enctype="multipart/form-data">
                   <div class="card">
                       <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       </div>
                       <button type="submit" class="btn btn-primary">
                           Login
                       </button>
                   </div>
               </form>
           </div>
       </div>
   </div>
{% endblock %}

users/templates/users/profile_manager.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-4"></div>
        <div class="col-5">
            <div class="card">
                <div class="card-header">
                    <div class="card-title">
                        Change {{ user }}'s activity
                    </div>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.is_active }} : Activity

                </div>
            </div>
            <br>
             <button type="submit" class="btn btn-success">Confirm</button>
            <button><a href="{% url 'users:users_list' %}" class="btn btn-warning">Cancel</a></button>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
   <div class="container">
       <div class="row-6">
           <div class="col">
               <form class="row" method="post" enctype="multipart/form-data">
                   <div class="card">
                       <div class="card-body">
                           {% csrf_token %}
                           {{ form.as_p }}
                       </div>
                       <button type="submit" class="btn btn-primary">
                           Sign in
                       </button>
                   </div>
               </form>
           </div>
       </div>
   </div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% load my_tags %}

<title>Users</title>

<h2>Users</h2>
<br>
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% user_groups as user_group %}
    {% for object in objects_list %}
    {% if object.groups.all.0 == user_group %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ object.email }}</h3>
            </div>
            <div class="card-footer">
                <a class="mb-4"></a>
                <a class="btn btn-outline-primary " href="{% url 'users:profile_manager' object.pk %}">
                    {% if object.is_active %}
                    Block
                    {% else %}
                    Unblock
                    {% endif %}</a>
            </div>
        </div>
    </div>
    {% endif %}
    <br>
    {% endfor%}
</div>

{% endblock %}

users/templates/users/verification.html
{% extends 'mailing/base.html' %}
{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Enter code
                </h4>
              </div>
              <div class="card-body">
                  {% csrf_token %}

                  <input type="text" name="ver_code" class="form-control" id="ver_code" required>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success">Verify</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/verification_error.html
{% extends 'mailing/base.html' %}
{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Invalid code
                </h4>
              </div>
              <div class="card-body">
              </div>
              <div class="card-footer">
                  <a href="{% url 'users:verification_email' %}" class="btn btn-success">Try again</a>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}